# Use Node.js as the base image
FROM node:latest AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json .

# Install dependencies
RUN npm install --verbose

# Copy the application code
COPY . .

# Build the React + Vite application
RUN npm run build

EXPOSE 5173

CMD [ "npm", "run", "preview" ]